var UserConstants = {
  CURRENT_USER: 'CURRENT_USER',
  SELECTED_USER: 'SELECTED_USER',
  LOGOUT_CURRENT_USER: 'LOGOUT_CURRENT_USER',
  FOLLOW_USER: "FOLLOW_USER",
  UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER'
};

module.exports = UserConstants;
